### ISSUE TITLE
Add option to output easily parsible list of available scripts without extensions

### ISSUE THREAD

**Issue by jwalgran** [steventlamb/scripty#5]
Building tools that wrap scripty would be easier if it was possible to get a list of available script names without extensions:

```
$ scripty
choose one of the following:
check.sh
manage.sh
test.sh
```

Possible ``-l`` output

```
$ scripty -l
check
manage
test
```

**Comment by steventlamb** [comment]
Does it satisfy your use case to know that scripty can be executed with or without extensions?
```
$ scripty foo
# works
$ scripty foo.sh
# also works
```

**Comment by jwalgran** [comment]
I'm thinking about an Emacs script that wants to generate interactive functions.

```
scripty-check
scripty-manage
scripty-test
```

are better names than

```
scripty-check.sh
scripty-manage.sh
scripty-test.sh
```

You can argue that it is not scripty's responsibility to provide the short names, but it is already figuring them out anyway.
